### PR TITLE
Add RPI 3b arch

### PR DESCRIPTION
**Pull request by Macleykun**
Add's "support" for https://github.com/powenn/AltServer-Linux-ShellScript/issues/44

### CODE REVIEW

**Comment by powenn** [comment]
Does netmuxd support this arch?

**Comment by Macleykun** [comment]
Yus:
https://github.com/jkcoxson/netmuxd/releases/download/v0.1.4/armv7-linux-netmuxd
proof:
https://github.com/powenn/AltServer-Linux-ShellScript/issues/44#issuecomment-1288513970

Technically he could refresh with netmuxd but just not successfully. But it does run which is important.
However I do now realize armv7 release should be fetched for armv71/l.

**Comment by Macleykun** [comment]
um, heya
i'm not sure if you should've just merged withoud making any adjustsments...

https://github.com/NyaMisty/AltServer-Linux/releases/download/v0.0.5/AltServer-armv7l
doesn't work
but we have to allow armv7l but download: 
https://github.com/NyaMisty/AltServer-Linux/releases/download/v0.0.5/AltServer-armv7
(and i think it's wiser to make an adjustment on our side, then on netmuxd)

**Comment by Macleykun** [comment]
i have an idea, i'll submit just another one

**Comment by powenn** [comment]
I forgot to check is there existing AltServer Linux release for armv71

**Pull request merged**
