### PR TITLE
Fix previous pr by making armv7l as armv7

### PR DESCRIPTION
**Pull request by Macleykun**
not tested, but did this quick during work

### CODE REVIEW

**Comment by Macleykun** [comment]
wanan merge this @powenn >?

**Comment by powenn** [comment]
Have you tested it?

**Comment by Macleykun** [comment]
> Have you tested it?

Yup!

**Comment by powenn** [comment]
Okay, I merge it but the update will be published after netmuxd WiFi support updated,or is it already updated ?

**Comment by Macleykun** [comment]
It’s already updated :)
________________________________
Van: powen ***@***.***>
Verzonden: Sunday, November 27, 2022 12:14:29 PM
Aan: powenn/AltServer-Linux-ShellScript ***@***.***>
CC: Macley ***@***.***>; Author ***@***.***>
Onderwerp: Re: [powenn/AltServer-Linux-ShellScript] Fix previous pr by making armv7l as armv7 (PR #49)


Merged #49<https://github.com/powenn/AltServer-Linux-ShellScript/pull/49> into main.

**Comment by powenn** [comment]
works fine with the script ?

**Comment by Macleykun** [comment]
> works fine with the script ?

Yus! People may have to update their plist file with jitterbug tho
But other then that, all goodie :)

**Comment by powenn** [comment]
Could you write up details of it ? , I will add it to the update message

**Comment by Macleykun** [comment]
> Could you write up details of it ? , I will add it to the update message

I think it's also smart for you to test it out on your side, as i'm sadly a little bit in a rush.

https://github.com/osy/Jitterbug#pairing

download: https://github.com/osy/Jitterbug/releases
Run the program in the zip of the OS you're using right now.

Once you let it generate a pairing file, that .mobiledevicep file should then REPLACE the one in the /var/lib/lockdown/ (where the UUID/numbers are the same!!)

This should only be done once, then wifi refresh should always work :)

**Comment by powenn** [comment]
I will publish it when have time

**Pull request merged**
